config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights, only: [ :index ]
  resources :bookings, only: [ :show, :new, :create ]
  root to: "flights#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, presence: true, length: { is: 3 }

  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :flight_id, presence: true
  validates :number_of_tickets, presence: true, numericality: { only_integer: true, in: 1..4 }

  belongs_to :flight

  has_many :passengers, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :departure_airport, presence: true
  validates :arrival_airport, presence: true
  validates :start, presence: true
  validates :duration, presence: true, numericality: { in: 0..40 }

  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  validates :name, presence: true, length: { in: 1..30 }
  validates :email, format: { with: /\A[\w._%+-]+@[\w.-]+\.[a-zA-Z]{2,4}\z/,
  message: "please input valid email" }
  validates :booking_id, presence: true

  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id].to_i)
    @passengers = Array.new(params[:number_of_tickets].to_i, Passenger.new)
  end

  def create
    @booking = Booking.new(flight_id: booking_params[:flight_id].to_i, number_of_tickets: booking_params[:number_of_tickets].to_i)
    if @booking.save
      @passengers = Array.new(booking_params[:number_of_tickets].to_i, nil)
      i = 0
      @passengers.each do |passenger|
        @passengers[i] = @booking.passengers.build
        @passengers[i].name = booking_params[:passenger]["#{i}".to_sym][:name]
        @passengers[i].email = booking_params[:passenger]["#{i}".to_sym][:email]
        i += 1
      end
      if @passengers.all? { |p| p.valid? }
        @passengers.each do |p|
          p.save
        end
        redirect_to @booking
      else
        render :new, status: :unprocessable_entity
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id, :number_of_tickets, passenger: [ :name, :email ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |a| [ a.code, a.id ] }
    @start_date_options = Flight.select(:start).distinct.order("start").map { |g| [ g.start.to_date.strftime("%a %d %b %Y"), g.start.to_date ] }.uniq

    if submitted_query?
      # validate_ticket_number
      @matching_flights = Flight.where(departure_airport: params[:departure_code], arrival_airport: params[:arrival_code], start: Date.parse(params[:date])..Date.parse(params[:date])+1).order("start")
    else
      @matching_flights = nil
    end
  end

  private
  def submitted_query?
    params.has_key?(:departure_code) && params.has_key?(:arrival_code) && params.has_key?(:passengers_number) && params.has_key?(:date)
  end

  def validate_ticket_number
    # does not work
    params[:passengers_number] = params[:passengers_number].clamp(1, 4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h2>Book tickets</h2>

Flight ID: <%= @flight.id %><br>
DateTime: <%= @flight.start %><br>
From: <%= @flight.departure_airport.code %><br>
To: <%= @flight.arrival_airport.code %><br>
<br>
<%= form_with model: @booking do |form| %>
    <% i = 0 %>
    <% @passengers.each do |passenger| %>
        <%= form.fields_for passenger, index: i do |sub_form| %>
            <h4>Passenger <%= i = i + 1 %></h4>
            <%= sub_form.label :name, "Name:" %>
            <%= sub_form.text_field :name %><br>
            <%= sub_form.label :email, "Email:" %>
            <%= sub_form.text_field :email %><br>
        <% end %>
        <br>
        <%= form.hidden_field :flight_id, value: @flight.id %>
        <%= form.hidden_field :number_of_tickets, value: params[:number_of_tickets] %>
    <% end %>
    <%= form.submit "Confirm" %>
<% end %>
<br>
<%= link_to "Cancel", root_path %>

app/views/bookings/show.html.erb
<h2>Booking Details</h2>
ID: <%= @booking.id %><br>
Flight ID: <%= @booking.flight.id %><br>
DateTime: <%= @booking.flight.start %><br>
From: <%= @booking.flight.departure_airport.code %><br>
To: <%= @booking.flight.arrival_airport.code %><br>
Passenger<%= @booking.passengers.length > 1 ? "s" : "" %>:<br>
<ul>
<% @booking.passengers.each do |p| %>
    <li><%= p.name %><br></li>
<% end %>
</ul>

app/views/flights/index.html.erb
<%= form_with url: flights_path, method: :get do |form| %>
    <%= form.label :departure_code, "Departure:" %>
    <%= select_tag(:departure_code, options_for_select(@airport_options, selected: params[:departure_code])) %>

    <%= form.label :arrival_code, "Arrival:" %>
    <%= select_tag(:arrival_code, options_for_select(@airport_options, selected: params[:arrival_code])) %>

    <%= form.label :passengers_number, "Number of passengers:" %>
    <%= form.select :passengers_number, [1,2,3,4], selected: params[:passengers_number] %>

    <%= form.label :date, "Date:" %>
    <%= select_tag(:date, options_for_select(@start_date_options, selected: params[:date])) %>

    <%= form.submit "Search" %>
<% end %>

<% if @matching_flights.nil? %>
    <h2>Search for the flights for you.</h2>
<% elsif @matching_flights.empty? %>
    <h2>No matching flights.</h2>
<% else %>
    <%= form_with url: new_booking_path, method: :get do |form| %>
        <%= form.collection_radio_buttons :flight_id, @matching_flights, :id, lambda{ |i| i.start.strftime("%H:%M") } %>
        <%= form.hidden_field :number_of_tickets, value: params[:passengers_number] %>
    <br>
    <%= form.submit "Book" %>
    <% end %>
<% end %>
<br>
<%= link_to "Clear", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>